# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Frank Bautista
tagline:          'A Jekyll theme'
description:      'MSc candidate and physicist from Unoversidad Nacional de Colombia. I am passionate about cycling, photography and physics'
url:              https://github.com/fjbautistas/fjbautistas.github.io/
baseurl:          /

author:
  name:           'Frank Bautista'
  url:            https://twitter.com/fjbautistas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fjbautistas
